Fixes for NWA
MutinyWallet/mutiny-node pull request #1061
Opened 2024-03-09 16:28 UTC by benthecarman

Cleaned up some code while I was at it. Main things that fixed the issue was broadcasting the auth event to all of our relays and not putting the relay in the auth event when it wasn't needed. This fixes when I was able to reproduce with zapple-pay, not sure if it fixes with nostr.wine @nostr-wine should it send me an invoice right away

Closes #1057

2024-03-09 16:43 UTC, nostr-wine commented
Same issue testing for me. 

Connection Event ID: 21020f1b151bc9ca70477acc1440d6bc7ef37107c7f365e60208db406549fcbf
Wallet pubkey: a6f327a3c1b6ab97b891940fc7c54f90c7717af3380d200875a854a1f7590f7f

pay_invoice IDs: 0441906fc6d12fdeb6c12dac24dc7fcbe380dbc851310615e244140f45e4886b, 77b1a102178d02e647c041d29d48066a96d8b14769accde6c852ed1833cd5b2d, cb1b61d2bdd20331839e447d1b9c6e35b882f17f1e217f1df80355d7379fe8ef

2024-03-09 19:35 UTC, TonyGiorgio requested changes

2024-03-09 19:35 UTC, TonyGiorgio commented on mutiny-core/src/nostr/mod.rs
> +        relays.push(DEFAULT_RELAY.to_string()); // add in case it's not in the list
you're pushing the same thing twice.

2024-03-19 01:57 UTC, TonyGiorgio commented
> Same issue testing for me.
> 
> Connection Event ID: 21020f1b151bc9ca70477acc1440d6bc7ef37107c7f365e60208db406549fcbf Wallet pubkey: a6f327a3c1b6ab97b891940fc7c54f90c7717af3380d200875a854a1f7590f7f
> 
> pay_invoice IDs: 0441906fc6d12fdeb6c12dac24dc7fcbe380dbc851310615e244140f45e4886b, 77b1a102178d02e647c041d29d48066a96d8b14769accde6c852ed1833cd5b2d, cb1b61d2bdd20331839e447d1b9c6e35b882f17f1e217f1df80355d7379fe8ef
> 
> EDIT: I just sent your pubkey one now as well if its helpful. ID is f38949e5d67b3d12031b5b311172a961e792ef5051da26d9963b1799e3b467fe

Nothing would have changed server side with this PR. This is on the wallet, so it wouldn't be fixed for you unless you recompiled mutiny-node and imported it into your own instance of mutiny-web. 

If @benthecarman can fix the minor PR feedback change, we can deploy this in the next few weeks for you to test again.

2024-03-19 19:30 UTC, TonyGiorgio approved these changes

2024-03-19 19:30 UTC, TonyGiorgio commented
needs rebase

2024-03-19 19:46 UTC, merged