Replace instant dependency with web-time
MutinyWallet/mutiny-node pull request #1098
Opened 2024-04-01 00:35 UTC by DanGould

web-time offers a number of advantages over the instant crate

- Actively maintained
- Stable 1.x API
- Exact std::time  replacement
- Compatible with rustls pki-types web feature
- Re-exports std::time when not targeting wasm32-unknown-unknown without pulling in any dependencies

2024-04-02 22:57 UTC, benthecarman requested changes
i'd rather use `std::time` when we aren't on wasm32. no need to use this dep in those instances

2024-04-02 23:19 UTC, DanGould commented
This crate is just an alias for `std::time` when we aren't on wasm32-unknown-unknown. This dep will not be used in those instances thanks to rust's dead code elimination.

See: https://github.com/daxpedda/web-time/blob/main/src/lib.rs

2024-04-02 23:24 UTC, benthecarman commented
Yeah but then we need to trust that dep vs just doing less of 10 lines of code to handle it ourself

2024-04-03 03:50 UTC, benthecarman approved these changes
lgtm

2024-04-03 14:32 UTC, DanGould commented
Thanks for the prompt review

2024-04-11 02:45 UTC, merged