Bump payjoin version 0.13.1
MutinyWallet/mutiny-node pull request #1242
Opened 2024-08-13 20:41 UTC by DanGould

2024-08-13 20:44 UTC, benthecarman approved these changes
ack, fixes a vuln

2024-08-13 21:21 UTC, TonyGiorgio approved these changes

2024-08-13 21:22 UTC, TonyGiorgio requested changes
I reran a test but if that doesn't work then some dep change messed something up

2024-08-13 21:58 UTC, benthecarman commented
test was failing from you deleting your nostr account so it couldn't sync nostr contacts, changed it to jack's npub to fix

2024-08-14 02:06 UTC, TonyGiorgio approved these changes

2024-08-14 02:06 UTC, merged