Request NWC events every 10 seconds
MutinyWallet/mutiny-node pull request #540
Opened 2023-05-26 23:07 UTC by benthecarman

Made it so we request nostr wallet connect events every 10 seconds, this makes it so we don't have to make it so blastr sends events to concurrent subscriptions. This also will help with failed invoices, we will reattempt them on the next loop.

2023-05-27 03:06 UTC, TonyGiorgio requested changes
Blastr will delete events after they have been sent to the client right? I think this will work to continuously request events. But if starting from an off state, then we should either: 
- add a 5 or 10 second sleep before requesting events
- introduce some wait till connected to LSP
- add some retry handling to events pulled down from the relay

2023-05-27 03:06 UTC, TonyGiorgio commented on mutiny-core/src/lib.rs
> +                                    utils::sleep(10_000).await;
Ideally this is stop compatible like this: 

```
                // wait up to 5s, checking graceful shutdown check each 1s.
                for _ in 0..5 {
                    if stop.load(Ordering::Relaxed) {
                        logging_db.stop();
                        return;
                    }
                    sleep(1_000).await;
                }
```

2023-05-27 03:06 UTC, TonyGiorgio commented on mutiny-core/src/lib.rs
> +                                    // after we process all events, sleep for 5 seconds
```suggestion
                                    // after we process all events, sleep for 10 seconds
```

2023-05-27 04:01 UTC, benthecarman commented
> Blastr will delete events after they have been sent to the client right? 

It deletes after the client sends a response event

2023-05-28 21:49 UTC, TonyGiorgio commented
> > Blastr will delete events after they have been sent to the client right?
> 
> It deletes after the client sends a response event

Okay that makes sense actually. I think after the minor changes above it should be good to go then.

2023-05-29 20:30 UTC, benthecarman commented
Changed so it waits for it to have usable channels and now the 10 second sleep between runs works with stops

2023-05-29 22:06 UTC, TonyGiorgio requested changes

2023-05-29 22:06 UTC, TonyGiorgio commented on mutiny-core/src/lib.rs
>                      continue;
This should be a break not a continue.

2023-05-29 22:10 UTC, TonyGiorgio approved these changes

2023-05-29 22:18 UTC, merged