Networking wasm split
MutinyWallet/mutiny-node pull request #549
Opened 2023-06-01 02:23 UTC by TonyGiorgio

- [x] Move connecting logic
- [x] Hide all proxy logic behind wasm flag
- [ ] Get alternative builds compiling properly
- [ ] Implement lightning-net-tokio for non wasm code

2023-06-07 21:54 UTC, TonyGiorgio commented
This is ready for review though Im going to keep working on the github actions for it.

2023-06-08 03:25 UTC, benthecarman commented
should delete this file

https://github.com/MutinyWallet/mutiny-node/blob/master/.cargo/config

2023-06-08 03:26 UTC, benthecarman commented on mutiny-core/Cargo.toml
> -getrandom = { version = "0.2", features = ["js"] }
can just remove this here and just in the wasm config add the feature

2023-06-08 03:30 UTC, TonyGiorgio commented
> should delete this file
> 
> https://github.com/MutinyWallet/mutiny-node/blob/master/.cargo/config

It causes problems with my IDE otherwise. I think we still need some default target runtime target and since mutiny-wasm is also here, I think we should keep it set to wasm.

2023-06-08 03:36 UTC, benthecarman requested changes
LFG, some small code smells I saw, will tests and give more review tomorrow

2023-06-08 03:36 UTC, benthecarman commented on mutiny-core/src/node.rs
> +        #[cfg(not(target_arch = "wasm32"))]
here too, the only diff is the `websocket_proxy_addr` I think you can just put that behind a build config

2023-06-08 03:36 UTC, benthecarman commented on mutiny-core/src/node.rs
> +                let connect_res = connect_peer_if_necessary(
same here

2023-06-08 03:37 UTC, TonyGiorgio commented on mutiny-core/src/nodemanager.rs
>                  websocket_proxy_addr.clone(),
I feel like I sometimes had problems doing that, I'll try again.

2023-06-08 03:39 UTC, TonyGiorgio commented on mutiny-core/src/utils.rs
> +    return std::time::SystemTime::now()
My thought was to just cut out a dependency if it wasn't needed, but I suppose it's fine?

2023-06-08 03:43 UTC, benthecarman commented on mutiny-core/src/utils.rs
> +    return std::time::SystemTime::now()
Yeah good point that's probably better, less risk

2023-06-08 16:02 UTC, TonyGiorgio commented on mutiny-core/src/nodemanager.rs
>                  websocket_proxy_addr.clone(),
Good catches, I also took the oppportunity to combine the `connect_peer` functions.

2023-06-08 20:57 UTC, benthecarman reviewed
`just test` just runs the browser tests, should add to it that it runs the normal tests too.
However, `cargo test` only works for me if we delete the `.cargo` folder. We also could move a lot of our tests to not need to run in the browser, maybe we just do that in a follow up

2023-06-08 20:57 UTC, benthecarman commented on mutiny-core/src/networking/proxy.rs
should put `PEER_PUBKEY` behind `#[cfg(feature = "ignored_tests")]` to get rid of the warning.

2023-06-08 20:57 UTC, benthecarman commented on mutiny-core/src/utils.rs
> +        tokio::task::spawn_local(future);
this didn't work for me when trying to create a mutiny-server

switching to this did 

`tokio::task::LocalSet::new().spawn_local(future);`

2023-06-08 20:57 UTC, benthecarman commented
Otherwise looks good to me! Awesome work!

2023-06-08 21:27 UTC, TonyGiorgio commented
Good catches. 

`just test` and `just clippy` should work for you now, without any need to delete the cargo config file.

2023-06-08 21:41 UTC, benthecarman commented on .github/workflows/test.yml
> +  core_tests_linux:
last thing, should add caching to these CI jobs

2023-06-08 21:54 UTC, benthecarman approved these changes

2023-06-08 22:08 UTC, merged