more ben: Add nwc profile to vss
MutinyWallet/mutiny-node pull request #691
Opened 2023-08-05 21:57 UTC by bennyhodl

Saves created NWC profiles to vss.

Version is updated on creating new NWC profiles in `indexed_db`. Could use some direction on checking the vss storage.

2023-08-07 16:59 UTC, TonyGiorgio commented
Nice. We should eventually have more things in VSS but kept it to critical data. However I can see NWC being annoying to keep adding if someone reset their wallet. We want to change to a more deterministic key generation approach for NWC based on the profile name, but haven't gotten around to that yet. We may have to do that first before this, since doing so will break all NWCs.

Quick code base looks alright, I'll have to let @benthecarman comment on the specifics since he has more experience with these two things.

2023-08-08 14:48 UTC, bennyhodl commented
@benthecarman rebased and squashed to one commit

2023-08-08 17:11 UTC, benthecarman requested changes
This still also doesn't handle backwards compat for reading the nwc configs from _before_ this PR. 

Also looks like there are some more places where we write the nwc storage without doing vss

2023-08-08 17:11 UTC, benthecarman commented on mutiny-core/src/nostr/mod.rs
> +    nwc_profile_version: Option<NwcProfileVersion>,
When this is `None` it is never set to be `Some` after it is updated. Probably what would be best is to not have this be optional and on init, if we don't have it, create a new one with version=0

2023-08-08 17:11 UTC, benthecarman commented on mutiny-core/src/nostr/mod.rs
> +        let nwc_profile_version = NwcProfileVersion::new();
this needs to be read from storage, otherwise you'll always be starting with version 0

2023-11-28 17:26 UTC, closed without merging