Less aggressive peer reconnection
MutinyWallet/mutiny-node pull request #942
Opened 2024-01-05 21:37 UTC by TonyGiorgio

One problem is LSP peer connection thread spawns and then this spawns and it tries to reconnect to LSP twice immediately after starting up. This should allow for some time to actually do the handshake. I don't care about waiting up to 30s before starting reconnect logic because if a connection fails immeidately upon startup, there's probably other factors at play. 

I've also moved from 5 second reconnect minimums to 10s.

2024-01-05 21:39 UTC, benthecarman commented
Overall looks good. I think this might break for users who have channels to peers that aren't their LSP. It would only connect to them after 30 seconds. Maybe a better approach is to combine this thread with the LSP thread.

2024-01-05 21:42 UTC, TonyGiorgio commented
> Overall looks good. I think this might break for users who have channels to peers that aren't their LSP. It would only connect to them after 30 seconds. Maybe a better approach is to combine this thread with the LSP thread.

Good point. I don't know why the seperation is there.

2024-01-09 20:10 UTC, TonyGiorgio commented
I still need to test it but this does the following: 

1. tries to connect to LSP node
2. tries to connect to non-lsp nodes
3. then after 30s will try to reconnect to any nodes that might have been disconnected

2024-01-09 20:24 UTC, benthecarman requested changes
looks like it has a clippy issue too

2024-01-09 20:24 UTC, benthecarman commented on mutiny-core/src/node.rs
> +            for _ in 0..10 {
should make this `0..INITIAL_RECONNECTION_DELAY`

2024-01-09 20:24 UTC, benthecarman commented on mutiny-core/src/node.rs
> +        if let Some(lsp) = lsp_client_copy.clone() {
nit: think you can use `as_ref()` here instead

2024-01-09 22:18 UTC, TonyGiorgio commented
Tested with/without an LSP and with/without another peer connected and both the init process and reconnecting after I switch off/on the wifi seemed to work.

2024-01-09 22:27 UTC, benthecarman approved these changes

2024-01-09 22:27 UTC, merged