Create index for sorted activity
MutinyWallet/mutiny-node pull request #999
Opened 2024-01-30 20:45 UTC by benthecarman

Now keeps a sorted index of our activity at all time. This should make our activity much faster with only a slight overhead increase.

2024-02-01 22:31 UTC, benthecarman commented
Changed to `limit`/`offset` instead of `start`/`until` as we talked irl

2024-02-02 11:49 UTC, TonyGiorgio requested changes
<img width="460" alt="Screenshot 2024-02-02 at 11 43 42 AM" src="https://github.com/MutinyWallet/mutiny-node/assets/101225832/5027f78e-dae9-406e-80c5-cd90cb68d700">

An unknown 0 sat on chain payment appeared during some channel closes.

<img width="452" alt="Screenshot 2024-02-02 at 11 47 15 AM" src="https://github.com/MutinyWallet/mutiny-node/assets/101225832/8fa47bef-ee52-4842-ac99-03c2abe482f9">

Multiple force close items are showing up when I only had one. 

Further, I cannot test this long enough without getting OOM issues.

2024-02-02 11:49 UTC, TonyGiorgio commented on mutiny-core/src/lib.rs
> +                }
We have `list_channel_closures` which is now no longer used or accessed, we should move the logic here into a method that lists channel closes which can be reusable, and remove the old one.

2024-02-02 11:49 UTC, TonyGiorgio commented on mutiny-core/src/lib.rs
> +            }
```suggestion
            let (start, end) = match (limit, offset) {
                (None, None) => (0, vec.len()),
                (Some(limit), Some(offset)) => {
                    let start = offset.min(vec.len());
                    let end = start.saturating_add(limit).min(vec.len());
                    (start, end)
                }
                (None, Some(offset)) => (offset.min(vec.len()), vec.len()),
                (Some(limit), None) => (0, limit.min(vec.len())),
            };

            vec[start..end].to_vec()
```

I think you can make this easier to read and safer by limiting the scope of what happens in the match. Just make it return the start and end and only need to call `to_vec()` in one place.

2024-02-02 11:51 UTC, TonyGiorgio commented
<img width="459" alt="Screenshot 2024-02-02 at 11 50 40 AM" src="https://github.com/MutinyWallet/mutiny-node/assets/101225832/fe94c56c-1171-474c-b6e4-4e731d52482b">

This lightning payment is showing up between the older on chain force closes that are duplicated

2024-02-03 18:00 UTC, benthecarman commented
Fixed all the duplication errors which also seemed to fixed the crashing for me too, curious if it helps for you as well.

2024-03-21 04:27 UTC, TonyGiorgio commented
What if we did this and defaulted the activity list to the last ~30 items? 

My phone is starting to get very slow. And having the new social home screen basically being a "view all"  for the transaction list, I would rather it not be that much.

2024-03-21 04:28 UTC, benthecarman commented
Makes sense to me, can rebase

2024-03-21 20:02 UTC, TonyGiorgio approved these changes
Code looks good. If you just want to test it to make sure it works with current mutiny master, that would be great.

2024-03-21 21:19 UTC, benthecarman commented
Found a potential index out of bounds error when testing, fixed it and added tests. Otherwise everything else felt good

2024-03-21 21:20 UTC, TonyGiorgio approved these changes

2024-03-21 21:26 UTC, benthecarman commented
sorry last push, chatgpt told me another check to add just in case:

```
// handle start > end
if start > end {
	return vec![];
}
```

2024-03-21 21:42 UTC, merged